# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 19:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kaaluleht', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(default=datetime.date.today)),
                ('activity', models.CharField(max_length=100)),
                ('avg_pulse', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Average Pulse')),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaaluleht.Kaal')),
            ],
        ),
    ]
