# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fit_notes', '0002_auto_20170704_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='eventID',
            new_name='user',
        ),
    ]
